from ubuntu:24.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt-get install --yes git && \
    apt-get install --yes cmake && \
    apt-get install --yes build-essential

RUN git clone https://github.com/google/googletest gtest && \
    cd gtest && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make install