name: Build | Google Test Docker Image
on:
  workflow_dispatch:
    inputs:
      PUSH_TO_REGISTRY:
        type: boolean
        description: Push to Registry
        required: true
        default: false

      DOCKER_TAG:
        type: string
        description: Docker Tag
        required: true
        default: 'NIGHTLY'

      USE_BRANCH_AS_DOCKER_TAG:
        type: boolean
        description: Use branch name as docker tag
        required: true
        default: true

jobs:
  build-images:
    runs-on: ubuntu-24.04
    steps:

      - name: Set PUSH_TO_REGISTRY for Scheduled Run
        if: github.event_name == 'schedule'
        run: echo "PUSH_TO_REGISTRY=true" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine current branch
        run: |
          if [ "${{ inputs.USE_BRANCH_AS_DOCKER_TAG" == 'true' && $GITHUB_REF != 'refs/heads/main' ]; then
            echo "BUILD_TAG=swatkat1977/duplitrace_gtest:${GITHUB_REF##*/}" >> "$GITHUB_ENV"
              echo "|=> Docker tag : ${GITHUB_REF##*/}"
            else  
            if [ "${{ inputs.DOCKER_TAG }}" = "NIGHTLY" ]; then
              echo "|=> Docker tag : NIGHTLY"
              echo "BUILD_TAG=swatkat1977/duplitrace_gtest:NIGHTLY" >> "$GITHUB_ENV"
            else
              echo "|=> Docker tag : ${{ inputs.DOCKER_TAG }}"
              echo "BUILD_TAG=swatkat1977/duplitrace_gtest:${{ inputs.docker_tag }}" >> "$GITHUB_ENV"
            fi
          fi

      #- name: Build and push Docker Image
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    file: docker/Dockerfile.googleTest
      #    push: ${{ inputs.PUSH_TO_REGISTRY }}
      #    no-cache: true
      #    tags: ${{ env.BUILD_TAG }}
      #    platforms: |
      #        linux/arm64
      #        linux/amd64
