name: Build | Google Test Docker Image
on:
  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        description: Push to Registry
        required: true

      docker_tag:
        type: string
        description: Docker Tag
        required: true
        default: 'NIGHTLY'

jobs:
  build-images:
    runs-on: ubuntu-24.04
    steps:

      - name: Set push_to_registry for Scheduled Run
        if: github.event_name == 'schedule'
        run: echo "push_to_registry=true" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine current branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "BUILD_TAG=duplitrace/duplitrace_gtest:LATEST" >> "$GITHUB_ENV"
          else
              echo "BUILD_TAG=duplitrace/duplitrace_gtest:${GITHUB_REF##*/}" >> "$GITHUB_ENV"
          fi

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.googleTest
          push: ${{ inputs.push_to_registry }}
          no-cache: true
          tags: ${{ env.BUILD_TAG }}
          platforms: |
              linux/arm64
              linux/amd64
