name: Build | Google Test Docker Image
on:
  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        description: Push to Registry
        required: true

      DOCKER_TAG:
        type: string
        description: Docker Tag
        required: true
        default: 'NIGHTLY'

jobs:
  build-images:
    runs-on: ubuntu-24.04
    steps:

      - name: Set push_to_registry for Scheduled Run
        if: github.event_name == 'schedule'
        run: echo "push_to_registry=true" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine current branch
        run: |
          if [ "${{ github.event.inputs.DOCKER_TAG }} = "NIGHTLY" ]; then
            echo "|=> Docker tag : NIGHTLY."
            echo "BUILD_TAG=duplitrace/duplitrace_gtest:NIGHTLY" >> "$GITHUB_ENV"            
          else
            echo "|=> Docker tag : $DOCKER_TAG"
            echo "BUILD_TAG=duplitrace/duplitrace_gtest:${{ github.event.inputs.docker_tag }}" >> "$GITHUB_ENV"
            exit 1
          fi
