name: Unit Tests | Common
on:
  schedule:
    - cron: '0 1 * * *'

  push:
    # Set branch to be invalid on purpose!
    branches:
      - 'invalid'

  workflow_dispatch:
    inputs:
      CUR_TIMESTAMP:
        description: Timestamp for the build
        required: false
        # Leave empty; we'll set it programmatically if not provided
        default: ''

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build --load -f docker/Dockerfile.unittests_common -t unittests_common:latest .

      - name: Debug: List Docker images
        run: docker images

      - name: Run Docker container
        run: docker run --name unittests_common -d unittests_common:latest

      #- name: Run Docker container
      #  run: |
      #    docker run --rm unittests_common:latest
