name: Unit Tests | Common
on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      CUR_TIMESTAMP:
        description: Timestamp for the build
        required: false
        # Leave empty; we'll set it programmatically if not provided
        default: ''

jobs:
  build-images:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Timestamp
        id: set-timestamp
        run: |
          if [[ "${{ github.event.inputs.timestamp }}" == "" ]]; then
            #echo "timestamp=$(date +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
            echo "timestamp=$(date +%Y-%m-%d_%H%M)" >> $GITHUB_ENV
          else
            echo "timestamp=${{ github.event.inputs.timestamp }}" >> $GITHUB_ENV
          fi
        env:
          TIMESTAMP: ${{ github.event.inputs.timestamp }}

      - name: Debug action
        run: |
          echo "timestamp : $timestamp"
          exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build -f docker/Dockerfile.unittests_common -t unittests_common:latest .

      - name: Run Docker container
        run: |
          docker run --rm unittests_common:latest
